name: Testing
on: [ push, pull_request ]

jobs:
  test-code:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install --frozen-lockfile

      - name: test
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test

      - name: build ~ checks with typescript
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
